on:
  workflow_dispatch:

name: Docs URL Alive Check
jobs:
  test:
    runs-on: ubuntu-22.04
    # don't run this action on forks
    if: github.repository_owner == 'kata-containers'
    env:
      target_branch: ${{ github.base_ref }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2
      env:
        GOPATH: ${{ runner.workspace }}/kata-containers
    - name: Set env
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: ./src/github.com/${{ github.repository }}
    # docs url alive check
    - name: Docs URL Alive Check
      run: |
        cd ${GOPATH}/src/github.com/${{ github.repository }} && make docs-url-alive-check
